#! /bin/sh

case "$1" in
    start)
        echo "Starting simpleserver"
        start-stop-daemon -S -n aesdsocket -a /bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping simpleserver"
        start-stop-daemon -K --signal 15 -n aesdsocket 
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0